# para instalar

```python
!conda install nome-do-pacote
!pip install nome-do-pacote
```

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import PIL

In [ ]:
# várias coisas do scikit-learn
from sklearn.datasets import fetch_openml
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
from sklearn.dummy import DummyClassifier # conta a classe popular, todos os novos vão para classe pop

# Mnist

In [ ]:
mnist = fetch_openml('mnist_784', as_frame=True)


In [ ]:
type(mnist)

sklearn.utils._bunch.Bunch

In [ ]:
mnist.keys()

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])

In [ ]:
print(mnist['DESCR'])

**Author**: Yann LeCun, Corinna Cortes, Christopher J.C. Burges  
**Source**: [MNIST Website](http://yann.lecun.com/exdb/mnist/) - Date unknown  
**Please cite**:  

The MNIST database of handwritten digits with 784 features, raw data available at: http://yann.lecun.com/exdb/mnist/. It can be split in a training set of the first 60,000 examples, and a test set of 10,000 examples  

It is a subset of a larger set available from NIST. The digits have been size-normalized and centered in a fixed-size image. It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting. The original black and white (bilevel) images from NIST were size normalized to fit in a 20x20 pixel box while preserving their aspect ratio. The resulting images contain grey levels as a result of the anti-aliasing technique used by the normalization algorithm. the images were centered in a 28x28 image b

In [ ]:
dados = mnist['data']

In [ ]:
dados.info() # metadados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Columns: 784 entries, pixel1 to pixel784
dtypes: int64(784)
memory usage: 418.7 MB


In [ ]:
resposta = mnist['target']

In [ ]:
resposta = resposta.astype(np.int64)

In [ ]:
resposta

,class
0,5
1,0
2,4
3,1
4,9
...,...
69995,2
69996,3
69997,4
69998,5


In [ ]:
some_digit = dados.iloc[0, :].to_numpy()

In [ ]:
some_digit

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [ ]:
some_digit.shape

(784,)

In [ ]:
img = some_digit.reshape(28, 28)

In [ ]:
img.dtype

dtype('int64')

In [ ]:
img = img.astype(np.uint8) # np.uint8 - 0 até 255

In [ ]:
PIL.Image.fromarray(img)

In [ ]:
resposta[0]

np.int64(5)

In [ ]:
X_train, X_test = dados.iloc[:60_000, :], dados.iloc[60_000:, :]
y_train, y_test = resposta.iloc[:60_000].astype(np.int64), resposta.iloc[60_000:].astype(np.int64)

# Treinando um Classificador Binário

In [ ]:
X_train

,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,pixel10,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [ ]:
y_train_5 = y_train == 5
y_test_5 = y_test == 5

In [ ]:
y_train_5

,class
0,True
1,False
2,False
3,False
4,False
...,...
59995,False
59996,False
59997,True
59998,False


In [ ]:
sgd_clf = SGDClassifier(random_state=42)

In [ ]:
sgd_clf.fit(X_train, y_train_5)

SGDClassifier(random_state=42)

In [ ]:
y_train_5

,class
0,True
1,False
2,False
3,False
4,False
...,...
59995,False
59996,False
59997,True
59998,False


In [ ]:
some_digit.shape

(784,)

In [ ]:
sgd_clf.predict(some_digit.reshape(1, 784))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(


array([ True])

In [ ]:
acuracias = cross_val_score(sgd_clf, X_train, y_train_5, scoring='accuracy', cv=3)

In [ ]:
acuracias

array([0.95035, 0.96035, 0.9604 ])

In [ ]:
zero_r = DummyClassifier()

In [ ]:
zero_r.fit(X_train, y_train_5)

DummyClassifier()

In [ ]:
acuracias_zero_r = cross_val_score(zero_r, X_train, y_train_5, scoring='accuracy', cv=3)

In [ ]:
acuracias_zero_r

array([0.90965, 0.90965, 0.90965])